[application]

# App (Project) Name
name = "Lentos"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[desktop.app]

# HTML title tag content
title = "Lentos"

# include `assets` in web platform
[desktop.resource]

# CSS style file
style = ["tailwind.css"]

# Javascript code file
script = []

[desktop.watcher]
reload_html = true

watch_path = ["src", "public"]

index_on_404 = true

[web.app]

# HTML title tag content
title = "Lentos"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# uncomment line below if using Router
index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# serve: [dev-server] only

# CSS style file
style = []

# Javascript code file
script = []
